import type { Grade, Exam, Resource } from '@/lib/types';

export const grades: Grade[] = [
  { id: 9, name: 'Grade 9' },
  { id: 10, name: 'Grade 10' },
  { id: 11, name: 'Grade 11' },
  { id: 12, name: 'Grade 12' },
];

export const exams: Exam[] = [
  {
    id: 'school-final-10',
    name: 'School Final Exam',
    gradeIds: [10],
    subjectWeightage: [
      { subject: 'Mathematics', weightage: 25 },
      { subject: 'Science', weightage: 25 },
      { subject: 'English', weightage: 20 },
      { subject: 'Social Studies', weightage: 20 },
      { subject: 'Language', weightage: 10 },
    ],
  },
  {
    id: 'school-final-12',
    name: 'School Final Exam',
    gradeIds: [12],
    subjectWeightage: [
      { subject: 'Physics', weightage: 25 },
      { subject: 'Chemistry', weightage: 25 },
      { subject: 'Mathematics', weightage: 25 },
      { subject: 'English', weightage: 15 },
      { subject: 'Computer Science', weightage: 10 },
    ],
  },
  {
    id: 'engineering-entrance',
    name: 'Engineering Entrance Exam',
    gradeIds: [11, 12],
    subjectWeightage: [
      { subject: 'Physics', weightage: 33 },
      { subject: 'Chemistry', weightage: 33 },
      { subject: 'Mathematics', weightage: 34 },
    ],
  },
  {
    id: 'medical-entrance',
    name: 'Medical Entrance Exam',
    gradeIds: [11, 12],
    subjectWeightage: [
      { subject: 'Physics', weightage: 25 },
      { subject: 'Chemistry', weightage: 25 },
      { subject: 'Biology', weightage: 50 },
    ],
  },
];

export const resources: Resource[] = [
  {
    id: 'res-1',
    title: 'Introduction to Algebra',
    description: 'A comprehensive video lesson covering the fundamentals of algebra.',
    type: 'YouTube',
    topic: 'Mathematics',
    difficulty: 'Beginner',
    url: 'https://www.youtube.com/',
    gradeId: 9,
    examIds: ['school-final-10'],
    imageId: 'algebra-basics',
  },
  {
    id: 'res-2',
    title: 'Calculus for Beginners',
    description: 'Master the basics of calculus with this engaging YouTube series.',
    type: 'YouTube',
    topic: 'Mathematics',
    difficulty: 'Intermediate',
    url: 'https://www.youtube.com/',
    gradeId: 11,
    examIds: ['engineering-entrance', 'school-final-12'],
    imageId: 'calculus-video',
  },
  {
    id: 'res-3',
    title: 'Newton\'s Laws of Motion',
    description: 'Downloadable PDF notes explaining Newton\'s three laws of motion with examples.',
    type: 'PDF',
    topic: 'Physics',
    difficulty: 'Beginner',
    url: '#',
    gradeId: 10,
    examIds: ['school-final-10', 'engineering-entrance'],
    imageId: 'physics-notes',
  },
  {
    id: 'res-4',
    title: 'Organic Chemistry Past Paper',
    description: 'Practice with a previous year\'s exam paper on organic chemistry, with solutions.',
    type: 'Past Paper',
    topic: 'Chemistry',
    difficulty: 'Advanced',
    url: '#',
    gradeId: 12,
    examIds: ['school-final-12', 'engineering-entrance', 'medical-entrance'],
    imageId: 'chemistry-paper',
  },
  {
    id: 'res-5',
    title: 'Cell Biology Fundamentals',
    description: 'An introductory video on the structure and function of cells.',
    type: 'YouTube',
    topic: 'Biology',
    difficulty: 'Beginner',
    url: 'https://www.youtube.com/',
    gradeId: 11,
    examIds: ['medical-entrance'],
    imageId: 'biology-basics',
  },
  {
    id: 'res-6',
    title: 'Indian Freedom Struggle',
    description: 'Detailed notes on the key events of the Indian independence movement.',
    type: 'PDF',
    topic: 'Social Studies',
    difficulty: 'Intermediate',
    url: '#',
    gradeId: 10,
    examIds: ['school-final-10'],
    imageId: 'history-lesson',
  },
  {
    id: 'res-7',
    title: '2022 Engineering Entrance Paper',
    description: 'Full question paper from the 2022 exam with a complete answer key.',
    type: 'Past Paper',
    topic: 'General',
    difficulty: 'Advanced',
    url: '#',
    gradeId: 12,
    examIds: ['engineering-entrance'],
    imageId: 'reasoning-puzzle',
  },
  {
    id: 'res-8',
    title: 'Shakespeare\'s Macbeth Analysis',
    description: 'An in-depth video analysis of themes and characters in Macbeth.',
    type: 'YouTube',
    topic: 'English',
    difficulty: 'Intermediate',
    url: 'https://www.youtube.com/',
    gradeId: 10,
    examIds: ['school-final-10'],
    imageId: 'literature-paper',
  },
  {
    id: 'res-9',
    title: 'Grade 10 Science Notes',
    description: 'Complete notes for Grade 10 Science covering Physics, Chemistry, and Biology.',
    type: 'PDF',
    topic: 'Science',
    difficulty: 'Intermediate',
    url: '#',
    gradeId: 10,
    examIds: ['school-final-10'],
    imageId: 'science-notes',
  },
  {
    id: 'res-10',
    title: 'Grade 12 Physics Past Paper',
    description: 'A past paper for Grade 12 Physics final exam.',
    type: 'Past Paper',
    topic: 'Physics',
    difficulty: 'Advanced',
    url: '#',
    gradeId: 12,
    examIds: ['school-final-12', 'engineering-entrance'],
    imageId: 'physics-paper',
  },
  {
    id: 'res-11',
    title: 'Human Anatomy 101',
    description: 'A YouTube series covering the basics of human anatomy for medical aspirants.',
    type: 'YouTube',
    topic: 'Biology',
    difficulty: 'Intermediate',
    url: 'https://www.youtube.com/',
    gradeId: 11,
    examIds: ['medical-entrance'],
    imageId: 'human-anatomy',
  },
  {
    id: 'res-12',
    title: 'Grade 10 Maths Past Paper',
    description: 'A past paper for the Grade 10 final exam in Mathematics.',
    type: 'Past Paper',
    topic: 'Mathematics',
    difficulty: 'Intermediate',
    url: '#',
    gradeId: 10,
    examIds: ['school-final-10'],
    imageId: 'math-paper',
  }
];
